apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: petstore-api
        image: ghcr.io/aorjoa/devops-java-example:e716de5626578245fbcd53934fe63aab832e18b7
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
